src/EngiShopBundle/Entity/Product.php
<?php

namespace EngiShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * Product
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="EngiShopBundle\Entity\ProductRepository")
 */
class Product
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=255)
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="descriptionExtended", type="text")
     */
    private $descriptionExtended;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="float")
     */
    private $price;

    /**
     * @var boolean
     *
     * @ORM\Column(name="featured", type="boolean")
     */
    private $featured;

    /**
     * @var boolean
     *
     * @ORM\Column(name="active", type="boolean")
     */
    private $active;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;

    /**
     * @var File
     *
     * @ORM\OneToOne(targetEntity="File", cascade={"persist", "remove"}, orphanRemoval=true, fetch="EAGER")
     */
    private $image;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="products", fetch="EAGER")
     */
    private $category;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Product
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param string $description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @return string
     */
    public function getDescriptionExtended()
    {
        return $this->descriptionExtended;
    }

    /**
     * @param string $descriptionExtended
     * @return $this
     */
    public function setDescriptionExtended($descriptionExtended)
    {
        $this->descriptionExtended = $descriptionExtended;
        return $this;
    }

    /**
     * @param float $price
     * @return $this
     */
    public function setPrice($price)
    {
        $this->price = $price;
        return $this;
    }

    /**
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param boolean $active
     * @return $this
     */
    public function setActive($active)
    {
        $this->active = $active;
        return $this;
    }

    /**
     * @return boolean
     */
    public function isActive()
    {
        return $this->active;
    }

    /**
     * @param boolean $featured
     * @return $this
     */
    public function setFeatured($featured)
    {
        $this->featured = $featured;
        return $this;
    }

    /**
     * @return boolean
     */
    public function getFeatured()
    {
        return $this->featured;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Product
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \EngiShopBundle\Entity\File $image
     * @return $this
     */
    public function setImage(File $image)
    {
        $this->image = $image;
        return $this;
    }

    /**
     * @return \EngiShopBundle\Entity\File
     */
    public function getImage()
    {
        return $this->image;
    }

    public function getImagePath()
    {
        return $this->image
            ? $this->image->getWebPath()
            : 'resources/img/no-image.jpg';
    }

    public function removeImage()
    {
        $this->image = null;
        return $this;
    }

    /**
     * @param \EngiShopBundle\Entity\Category $category
     * @return $this
     */
    public function setCategory($category)
    {
        $this->category = $category;
        return $this;
    }

    /**
     * @return \EngiShopBundle\Entity\Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata) {
        $metadata->addPropertyConstraint('slug', new NotNull(array('message' => 'Ta wartość nie powinna być pusta.')));
        $metadata->addPropertyConstraint('slug', new Regex(array(
            'message' => 'Ta wartość nie jest poprawnym adresem.',
            'pattern' => '/^[a-zA-Z0-9_\-\+]+$/'
        )));
    }

    public function __toString()
    {
        return $this->getName() ?: '';
    }
}

src/EngiShopBundle/Form/Type/ProductType.php
<?php

namespace EngiShopBundle\Form\Type;

use Doctrine\ORM\EntityRepository;
use EngiShopBundle\Form\Type\FileImageType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', [
                'label' => 'Nazwa'
            ])
            ->add('description', 'textarea', [
                'label' => 'Opis',
                'attr' => [
                    'rows' => 10
                ]
            ])
            ->add('descriptionExtended', 'textarea', [
                'label' => 'Rozszerzony opis',
                'attr' => [
                    'rows' => 10
                ]
            ])
            ->add('price', 'number', [
                'label' => 'Cena'
            ])
            ->add('category', 'entity', [
                'label' => 'Kategoria',
                'required' => 'false',
                'class' => 'EngiShopBundle:Category',
                'empty_value' => '-- Brak --',
                'query_builder' => function(EntityRepository $er) {
                    return $er->createQueryBuilder('c')
                        ->orderBy('c.name');
                }
            ])
            ->add('slug', 'text', [
                'label' => 'Adres'
            ])
            ->add('featured', 'checkbox', [
                'label' => 'Na główną?',
                'required' => false
            ])
            ->add('active', 'checkbox', [
                'label' => 'Aktywny?',
                'required' => false
            ])
            ->add('image', new FileImageType(), [
                'cascade_validation' => true,
                'required' => false,
                'data_class' => 'EngiShopBundle\Entity\File'
            ]);

    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver
            ->setDefaults([
                'data_class' => 'EngiShopBundle\Entity\Product'
            ]);
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'engishop_product';
    }
} 

src/EngiShopBundle/Controller/ProductController.php
<?php

namespace EngiShopBundle\Controller;

use EngiShopBundle\Entity\Product;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class ProductController extends Base\FrontController
{
    /**
     * @Template
     * @param Product $product
     * @return array
     */
    public function showAction(Product $product)
    {
        return [
            'product' => $product
        ];
    }
}

src/EngiShopBundle/Resources/views/Product/index.html.twig
{% extends 'JKPAdminBundle::layout.html.twig' %}
{% block header %}
    <h1>Produkty</h1>
{% endblock header %}
{% block content %}
    <div>
        <a class="btn btn-primary pull-right" href="{{ path('jkp_admin_product_new') }}"><span class="glyphicon glyphicon-plus"></span> Nowy produkt</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nazwa</th>
                <th>Adres</th>
                <th>Kategoria</th>
                <th>Cena</th>
                <th>Status</th>
                <th>Na głównej</th>
                <th>Utworzony</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>#{{ product.id }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.slug }}</td>
                    <td><strong>{% if product.category %}{{ product.category }}{% else %}-{% endif %}</strong></td>
                    <td><strong>{{ product.price }} ZŁ</strong></td>
                    <td>{% if product.active %}<span class="label label-success">Aktywny</span>{% else %}<span class="label label-danger">Nieaktywny</span>{% endif %}</td>
                    <td>{% if product.featured %}<span class="label label-primary">Tak</span>{% else %}<span class="label label-default">Nie</span>{% endif %}</td>
                    <td>{{ product.createdAt | date('d-m-Y') }}</td>
                    <td class="actions">
                        <form class="inline-block" action="{{ path('jkp_admin_product_switch', { 'id': product.id }) }}" method="post">
                            <button type="submit" class="btn btn-{% if product.active %}default{% else %}primary{% endif %} btn-xs"><span class="glyphicon glyphicon-{% if product.active %}ban{% else %}ok{% endif %}-circle"></span> {% if product.active %}Dezaktywuj{% else %}Aktywuj{% endif %}</button>
                        </form>
                        <a class="btn btn-warning btn-xs" href="{{ path('jkp_admin_product_edit', { 'id': product.id }) }}"><span class="glyphicon glyphicon-pencil"></span> Edytuj</a>
                        <form class="inline-block" action="{{ path('jkp_admin_product_delete', { 'id': product.id }) }}" method="post">
                            <button type="submit" class="btn btn-danger btn-xs delete"><span class="glyphicon glyphicon-trash"></span> Usuń</button>
                        </form>
                    </td>
                </tr>
            {% else %}
                <tr class="table-empty-row">
                    <td colspan="7">
                        <h4><span class="glyphicon glyphicon-info-sign"></span> Nie ma żadnych produktów! Kliknij <a href="{{ path('jkp_admin_product_new') }}">tutaj</a> żeby dodać nowy produkt!</h4>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script type="text/javascript">
        $(function() {
            $('button.delete').click(function() {
                var $btn = $(this);

                bootbox.dialog({
                    message: 'Czy napewno chcesz usunąć ten produkt?',
                    title: 'Potwierdź decyzję',
                    buttons: {
                        no: {
                            label: 'Nie',
                            className: 'btn-default'
                        },
                        yes: {
                            label: 'Tak',
                            className: 'btn-danger',
                            callback: function() {
                                $btn.closest('form').submit();
                            }
                        }
                    }
                });

                return false;
            });
        });
    </script>
{% endblock content %}

src/EngiShopBundle/Resources/views/Product/show.html.twig
{% extends 'EngiShopBundle::layout.html.twig' %}

{% block content %}
    <div class="product-header">
        <h1>{{ product.name }}</h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p class="description">{{ product.description | nl2br }}</p>
            <div class="bordered-box">
                <div class="price-box">
                    <span class="price-label">Cena:</span>
                    <span class="price">{{ product.price | number_format(2, ',') }} PLN</span>
                </div>
                <div class="add-to-cart">
                    <form action="{{ path('engishop_front_cart_add', {id: product.id}) }}" method="post">
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart"></span> Dodaj do koszyka!</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <img src="/{{ product.imagePath }}" class="thumbnail" width="600">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p class="description">{{ product.descriptionExtended | nl2br }}</p>
        </div>
    </div>
{% endblock %}