src/EngiShopBundle/Entity/Cart.php
<?php

namespace EngiShopBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;

/**
 * Cart
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="EngiShopBundle\Entity\CartRepository")
 */
class Cart
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="CartItem", mappedBy="cart", fetch="EXTRA_LAZY", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $items;

    /**
     * @var User
     *
     * @ORM\OneToOne(targetEntity="User", inversedBy="cart")
     */
    private $user;

    public function __construct(User $user)
    {
        $this
            ->setUser($user)
            ->setItems(new ArrayCollection());
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return ArrayCollection
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * @param CartItem $item
     * @return $this
     */
    public function addItem(CartItem $item)
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setCart($this);
        }

        return $this;
    }

    /**
     * @param CartItem $item
     * @return $this
     */
    public function removeItem(CartItem $item)
    {
        $this->items->removeElement($item);
        return $this;
    }

    /**
     * @param ArrayCollection $items
     * @return $this
     */
    public function setItems(ArrayCollection $items)
    {
        $this->items = $items;
        return $this;
    }

    public function clearItems()
    {
        $this->items->clear();
        return $this;
    }

    /**
     * @param Product $product
     * @return CartItem|null
     */
    public function findProduct(Product $product)
    {
        $criteria = Criteria::create()->where(Criteria::expr()->eq('product', $product))->setMaxResults(1);

        return $this->items->matching($criteria)->first();
    }

    /**
     * @param integer $id
     * @return CartItem|null
     */
    public function findItem($id)
    {
        $criteria = Criteria::create()->where(Criteria::expr()->eq('id', $id));

        return $this->items->matching($criteria)->first();
    }

    /**
     * @return int
     */
    public function getItemsQuantity()
    {
        $count = 0;

        /** @var CartItem $item */
        foreach ($this->getItems() as $item) $count += $item->getQuantity();

        return $count;
    }

    /**
     * @return float
     */
    public function getTotal()
    {
        $total = 0;

        /** @var CartItem $item */
        foreach ($this->getItems() as $item) $total += $item->getTotal();

        return $total;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param User $user
     * @return $this
     */
    public function setUser(User $user)
    {
        $this->user = $user;
        $user->setCart($this);
        return $this;
    }
}

src/EngiShopBundle/Entity/CartItem.php
<?php

namespace EngiShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * CartItem
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="EngiShopBundle\Entity\CartItemRepository")
 */
class CartItem
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="quantity", type="integer")
     */
    private $quantity;

    /**
     * @var Product
     *
     * @ORM\ManyToOne(targetEntity="Product")
     */
    private $product;

    /**
     * @var Cart
     *
     * @ORM\ManyToOne(targetEntity="Cart", inversedBy="items")
     */
    private $cart;

    public function __construct(Product $product, $quantity = 1)
    {
        $this->setProduct($product)->setQuantity($quantity);
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     * @return CartItem
     */
    public function setQuantity($quantity)
    {
        if ($quantity < 0) $quantity = 0;

        $this->quantity = $quantity;
        return $this;
    }

    /**
     * Get quantity
     *
     * @return integer 
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * @param integer $quantity
     * @return $this
     */
    public function addQuantity($quantity)
    {
        $this->quantity += $quantity;
        return $this;
    }

    /**
     * @return Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * @param Product $product
     * @return $this
     */
    public function setProduct(Product $product)
    {
        $this->product = $product;
        return $this;
    }

    /**
     * @return Cart
     */
    public function getCart()
    {
        return $this->cart;
    }

    /**
     * @param Cart $cart
     * @return $this
     */
    public function setCart(Cart $cart)
    {
        $this->cart = $cart;
        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->getProduct()->getName();
    }

    /**
     * @return float
     */
    public function getPrice()
    {
        return $this->getProduct()->getPrice();
    }

    /**
     * @return float
     */
    public function getTotal()
    {
        return $this->getProduct()->getPrice() * $this->getQuantity();
    }
}

src/EngiShopBundle/Entity/OrderClass.php
<?php

namespace EngiShopBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * OrderClass
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="EngiShopBundle\Entity\OrderClassRepository")
 */
class OrderClass
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string")
     */
    private $address;

    /**
     * @ORM\Column(type="string")
     */
    private $address2;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $zip;

    /**
     * @ORM\Column(type="string")
     */
    private $city;

    /**
     * @ORM\Column(type="string")
     */
    private $state;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private $country;

    /**
     * @var boolean
     *
     * @ORM\Column(name="inProcess", type="boolean")
     */
    private $inProcess;

    /**
     * @var boolean
     *
     * @ORM\Column(name="completed", type="boolean")
     */
    private $completed;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(type="float")
     */
    private $discount;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="OrderItem", mappedBy="order", fetch="EXTRA_LAZY", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $items;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="orders")
     */
    private $user;

    public function __construct(User $user)
    {
        $this
            ->setCreatedAt(new \DateTime())
            ->setInProcess(false)
            ->setCompleted(false)
            ->setDiscount(0)
            ->setUser($user)
            ->setItems(new ArrayCollection());

        /** @var CartItem $item */
        foreach ($user->getCart()->getItems() as $item) {
            $this->addItem(new OrderItem($item));
        }
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param mixed $firstName
     * @return OrderClass
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param mixed $lastName
     * @return OrderClass
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param mixed $address
     * @return OrderClass
     */
    public function setAddress($address)
    {
        $this->address = $address;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAddress2()
    {
        return $this->address2;
    }

    /**
     * @param mixed $address2
     * @return OrderClass
     */
    public function setAddress2($address2)
    {
        $this->address2 = $address2;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * @param mixed $zip
     * @return OrderClass
     */
    public function setZip($zip)
    {
        $this->zip = $zip;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param mixed $city
     * @return OrderClass
     */
    public function setCity($city)
    {
        $this->city = $city;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * @param mixed $state
     * @return OrderClass
     */
    public function setState($state)
    {
        $this->state = $state;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param mixed $country
     * @return OrderClass
     */
    public function setCountry($country)
    {
        $this->country = $country;
        return $this;
    }

    /**
     * Set inProcess
     *
     * @param boolean $inProcess
     * @return OrderClass
     */
    public function setInProcess($inProcess)
    {
        $this->inProcess = $inProcess;

        return $this;
    }

    /**
     * Get inProcess
     *
     * @return boolean 
     */
    public function isInProcess()
    {
        return $this->inProcess;
    }

    /**
     * Set completed
     *
     * @param boolean $completed
     * @return OrderClass
     */
    public function setCompleted($completed)
    {
        $this->completed = $completed;

        return $this;
    }

    /**
     * Get completed
     *
     * @return boolean 
     */
    public function isCompleted()
    {
        return $this->completed;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return OrderClass
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return string
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * @param string $discount
     * @return OrderClass
     */
    public function setDiscount($discount)
    {
        $this->discount = $discount;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * @param OrderItem $item
     * @return $this
     */
    public function addItem(OrderItem $item)
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setOrder($this);
        }

        return $this;
    }

    /**
     * @param OrderItem $item
     * @return $this
     */
    public function removeItem(OrderItem $item)
    {
        $this->items->removeElement($item);
        return $this;
    }

    /**
     * @param ArrayCollection $items
     * @return OrderClass
     */
    public function setItems(ArrayCollection $items)
    {
        $this->items = $items;
        return $this;
    }

    /**
     * @return int
     */
    public function getItemsQuantity()
    {
        $count = 0;

        /** @var CartItem $item */
        foreach ($this->getItems() as $item) $count += $item->getQuantity();

        return $count;
    }

    /**
     * @return float
     */
    public function getTotal()
    {
        $total = 0;

        /** @var CartItem $item */
        foreach ($this->getItems() as $item) $total += $item->getTotal();

        return $total;
    }

    public function getTotalWithDiscount()
    {
        return $this->getTotal() * (1 - $this->getDiscount());
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param User $user
     * @return OrderClass
     */
    public function setUser(User $user)
    {
        $this->user = $user;

        $this
            ->setFirstName($user->getFirstName())
            ->setLastName($user->getLastName())
            ->setAddress($user->getAddress())
            ->setAddress2($user->getAddress2())
            ->setZip($user->getZip())
            ->setCity($user->getCity())
            ->setState($user->getState())
            ->setCountry($user->getCountry());

        $user->addOrder($this);

        return $this;
    }


}

src/EngiShopBundle/Form/Type/OrderType.php
<?php

namespace EngiShopBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName', 'text', ['label' => 'Imię'])
            ->add('lastName', 'text', ['label' => 'Nazwisko'])
            ->add('address', 'text', ['label' => 'Adres'])
            ->add('address2', 'text', ['label' => 'Adres c. d.'])
            ->add('zip', 'text', ['label' => 'Kod pocztowy'])
            ->add('city', 'text', ['label' => 'Miasto'])
            ->add('state', 'text', ['label' => 'Województwo'])
            ->add('country', 'country', ['label' => 'Kraj'])
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver
            ->setDefaults([
                'data_class' => 'EngiShopBundle\Entity\OrderClass'
            ]);
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'engishop_order';
    }
} 

src/EngiShopBundle/Controller/OrderController.php
<?php

namespace EngiShopBundle\Controller;

use EngiShopBundle\Entity\OrderClass;
use EngiShopBundle\Form\Type\OrderType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class OrderController extends Base\FrontController
{
    /**
     * @Template
     * @param Request $request
     * @return array
     */
    public function newAction(Request $request)
    {
        $cartHelper = $this->get('engishop.cart_helper');
        $discount = $cartHelper->getDiscount($request->request->get('discountCode'));

        $form = $this->createForm(new OrderType(), new OrderClass($this->getUser()));

        if ($form->handleRequest($request)->isValid()) {
            $this->getEm()->persist($form->getData()->setDiscount($discount));
            $cartHelper->getCart()->clearItems();
            $this->getEm()->flush();

            return $this->redirectToRoute('engishop_front_homepage');
        }

        return [
            'order' => $form->getData(),
            'discount' => $discount,
            'form' => $form->createView()
        ];
    }

    /**
     * @param OrderClass $order
     * @return array
     *
     * @Template
     */
    public function showAction(OrderClass $order)
    {
        if ($this->getUser() != $order->getUser()) {
            throw new AccessDeniedException;
        }

        return [
            'order' => $order
        ];
    }
}

src/EngiShopBundle/Resources/views/Order/new.html.twig
{% extends 'EngiShopBundle::layout.html.twig' %}

{% block content_main %}
    <h1>Złóż zamówienie</h1>

    <form class="contain-floats" action="{{ path('engishop_front_order_new') }}" method="post" {{ form_enctype(form) }}>
        <h2>Dane adresowe:</h2>

        {{ form_errors(form) }}

        {{ form_rest(form) }}

        <h2>Podsumowanie:</h2>

        <table class="table">
            <thead>
            <tr>
                <th>Lp.</th>
                <th>Przedmiot</th>
                <th>Cena (szt.)</th>
                <th>Ilość</th>
                <th>Cena (razem)</th>
            </tr>
            </thead>
            <tbody>
            {% for item in order.items %}
                <tr>
                    <td>#{{ loop.index }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.price | number_format(2, ',') }} zł</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.total | number_format(2, ',') }} zł</td>
                </tr>
            {% endfor %}
            {% if discount > 0 %}
                <tr>
                    <td colspan="2">&nbsp;</td>
                    <td>Razem:</td>
                    <td>{{ order.itemsQuantity }}</td>
                    <td>{{ order.total | number_format(2, ',') }} zł</td>
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                    <td><span class="discount">Zniżka:</span></td>
                    <td><span class="discount">-</span></td>
                    <td><span class="discount">-{{ discount * 100 }}%</span></td>
                </tr>
            {% endif %}
            <tr>
                <td colspan="2">&nbsp;</td>
                <td><span class="bold">Razem:</span></td>
                <td><span class="bold">{{ order.itemsQuantity }}</span></td>
                <td><span class="bold">{{ (order.total * (1 - discount)) | number_format(2, ',') }} zł</span></td>
            </tr>
            </tbody>
        </table>

        <div class="col-lg-offset-3 col-lg-8">
            <div class="buttons-wrap inline-block">
                <a href="{{ path('engishop_front_cart') }}" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span> Cofnij</a>
                <button type="submit" class="btn btn-primary">Zamów <span class="glyphicon glyphicon-chevron-right"></span></button>
                <input type="hidden" name="discountCode" value="{{ app.request.get('discountCode') }}">
            </div>
        </div>
    </form>

    <script type="text/javascript">
        $(function() {
            $('select').select2();
        });
    </script>
{% endblock content_main %}

src/EngiShopBundle/Resources/views/Order/show.html.twig
{% extends 'EngiShopBundle::layout.html.twig' %}

{% block content_main %}
    <h1 class="inline-block">Szczegóły zamówienia #{{ order.id }} </h1>
    <div class="pull-right">
        <h1 class="inline-block">Status: {% if order.completed %}<span class="label label-success">Zakończone</span>{% elseif order.inProcess %}<span class="label label-primary">W realizacji</span>{% else %}<span class="label label-warning">Oczekuje</span>{% endif %}</h1>
    </div>

    <h4>Złożone: <span class="glyphicon glyphicon-calendar"></span> {{ order.createdAt | localizeddate('long', 'none') }} <strong style="margin-left: 10px"><span class="glyphicon glyphicon-time"></span> {{ order.createdAt | date('H:i') }}</strong></h4>

    <div class="row">
        <div class="col-md-6">
            <h2>Zamawiający:</h2>

            <div class="user-details">
                <span class="user-name">{{ order.user.firstName }} {{ order.user.lastName }}</span>
                <span>{{ order.user }} (<a href="mailto:{{ order.user.email }}">{{ order.user.email }}</a>)</span>
                <span>{{ order.user.address }} {{ order.user.address2 }}</span>
                <span>{{ order.user.zip }} {{ order.user.city }}</span>
                <span>{{ order.user.country | country(app.request.locale) }}</span>
            </div>
        </div>
        <div class="col-md-6">
            <h2>Adres dostawy:</h2>

            <div class="user-details">
                <span class="user-name">{{ order.firstName }} {{ order.lastName }}</span>
                <span>{{ order.user }} (<a href="mailto:{{ order.user.email }}">{{ order.user.email }}</a>)</span>
                <span>{{ order.address }} {{ order.address2 }}</span>
                <span>{{ order.zip }} {{ order.city }}</span>
                <span>{{ order.country | country(app.request.locale) }}</span>
            </div>
        </div>
    </div>

    <h2>Przedmioty:</h2>

    <table class="table">
        <thead>
        <tr>
            <th>Lp.</th>
            <th>Przedmiot</th>
            <th>Cena (szt.)</th>
            <th>Ilość</th>
            <th>Cena (razem)</th>
        </tr>
        </thead>
        <tbody>
        {% for item in order.items %}
            <tr>
                <td>#{{ loop.index }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.price | number_format(2, ',') }} zł</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.total | number_format(2, ',') }} zł</td>
            </tr>
        {% endfor %}
        {% if order.discount > 0 %}
            <tr>
                <td colspan="2">&nbsp;</td>
                <td>Razem:</td>
                <td>{{ order.itemsQuantity }}</td>
                <td>{{ order.total | number_format(2, ',') }} zł</td>
            </tr>
            <tr>
                <td colspan="2">&nbsp;</td>
                <td><span class="discount">Zniżka:</span></td>
                <td><span class="discount">-</span></td>
                <td><span class="discount">-{{ order.discount * 100 }}%</span></td>
            </tr>
        {% endif %}
        <tr>
            <td colspan="2">&nbsp;</td>
            <td><span class="bold">Razem:</span></td>
            <td><span class="bold">{{ order.itemsQuantity }}</span></td>
            <td><span class="bold">{{ order.totalWithDiscount | number_format(2, ',') }} zł</span></td>
        </tr>
        </tbody>
    </table>

    <div class="pull-right">
        <a class="btn btn-default" href="{{ path('engishop_front_user_show') }}"><span class="glyphicon glyphicon-chevron-left"></span> Powrót</a>
    </div>

        <div class="clearfix"></div>
{% endblock %}